//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadSpring.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadSpring.Core.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Active field is required..
        /// </summary>
        internal static string Employee_Active_Required {
            get {
                return ResourceManager.GetString("Employee_Active_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 100 characters..
        /// </summary>
        internal static string Employee_Email_Length {
            get {
                return ResourceManager.GetString("Employee_Email_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        internal static string Employee_Email_Required {
            get {
                return ResourceManager.GetString("Employee_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 50 characters..
        /// </summary>
        internal static string Employee_JobTitle_Length {
            get {
                return ResourceManager.GetString("Employee_JobTitle_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Title field is required..
        /// </summary>
        internal static string Employee_JobTitle_Required {
            get {
                return ResourceManager.GetString("Employee_JobTitle_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 50 characters..
        /// </summary>
        internal static string Employee_LastName_Length {
            get {
                return ResourceManager.GetString("Employee_LastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName field is required..
        /// </summary>
        internal static string Employee_LastName_Required {
            get {
                return ResourceManager.GetString("Employee_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 50 characters..
        /// </summary>
        internal static string Employee_Location_Length {
            get {
                return ResourceManager.GetString("Employee_Location_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location field is required..
        /// </summary>
        internal static string Employee_Location_Required {
            get {
                return ResourceManager.GetString("Employee_Location_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 50 characters..
        /// </summary>
        internal static string Employee_MotherLastName_Length {
            get {
                return ResourceManager.GetString("Employee_MotherLastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MotherLastName field is required..
        /// </summary>
        internal static string Employee_MotherLastName_Required {
            get {
                return ResourceManager.GetString("Employee_MotherLastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 50 characters..
        /// </summary>
        internal static string Employee_Name_Length {
            get {
                return ResourceManager.GetString("Employee_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        internal static string Employee_Name_Required {
            get {
                return ResourceManager.GetString("Employee_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for the name must be a maximum of 20 characters..
        /// </summary>
        internal static string Employee_Phone_Length {
            get {
                return ResourceManager.GetString("Employee_Phone_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone field is required..
        /// </summary>
        internal static string Employee_Phone_Required {
            get {
                return ResourceManager.GetString("Employee_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Role field is required..
        /// </summary>
        internal static string Employee_RoleName_Required {
            get {
                return ResourceManager.GetString("Employee_RoleName_Required", resourceCulture);
            }
        }
    }
}
